# rubocop --auto-gen-config
# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 155

Metrics/BlockLength:
  Max: 30

Layout/EndOfLine:
  EnforcedStyle: lf
